name: Test Datalayer

on:
  pull_request:
    branches-ignore:
      - production
      - production-static
  push:

jobs:
  sqitch:
    name: Datalayer migration tests with Sqitch
    runs-on: ubuntu-latest
    env:
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}
      LOADER_SKIP_TEST_DOMAIN: 1

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Run test container.
      - name: Run sqitch revert to latest major version and then deploy to test reversibility
        run: docker compose run sqitch_revert && docker compose run --no-deps sqitch deploy --verify

  pgtap:
    name: Datalayer SQL tests with pgTAP
    runs-on: ubuntu-latest
    env:
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Run test container.
      - name: Run pg_tap tests in docker compose
        run: docker-compose run datalayer-test

  requests:
    name: Datalayer API tests with requests
    runs-on: ubuntu-latest
    env:
      SUPABASE_SERVICE_ROLE_KEY: ${{secrets.TEST_SERVICE_SUPABASE_KEY}}
      SUPABASE_ANON_KEY: ${{secrets.TEST_ANON_SUPABASE_KEY}}

    steps:
      # cf. https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # Copy all projet .sample.env into .env with the variables
      - name: Make .env files
        run: sh make_dot_env.sh

      # Run test container.
      - name: Run requests with restcli in docker compose
        run: docker-compose run datalayer-api-test
